databases:
  - name: kokushiex-db
    plan: starter
    databaseName: kokushiex
    user: kokushiex
    region: singapore

services:
  - type: web
    name: kokushiex-web
    runtime: docker
    region: singapore
    plan: starter
    dockerfilePath: Dockerfile.prod
    preDeployCommand: bundle exec rails db:prepare:production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kokushiex-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

  - type: cron
    name: kokushiex-cleanup-guests
    runtime: docker
    region: singapore
    plan: starter
    schedule: "0 18 * * *"
    dockerfilePath: Dockerfile.prod
    dockerCommand: bundle exec rake cleanup:guest_users
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kokushiex-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
