services:
  web:
    # build: .でdocker-compose.ymlと同じフォルダにDockerfileがあることを示す
    build: .
    # 毎回 rm tmp/pids/server.pid するのも手間であるため事前に手元で/tmp/pids/server.pidを削除する
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    ports:
      - 10000:3000
    depends_on:
      - db
    # railsでpryする用
    # true を指定することでコンテナを起動させ続ける。   
    tty: true
    # stdin_openとは標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true

  db:
    image: postgres:16
    # DBのレコードが日本語だと文字化けするので、utf8をセットする
    command: postgres -c 'log_statement=all' -c 'client_encoding=utf8'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
# PC上にdb-volumeという名前でデータ領域が作成される
# コンテナを作り直したとしてもPC上に残るようにするために設定
volumes:
  gem_data:
  postgre_data: