name: Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker container
      run: docker-compose build

    - name: Run Docker container
      run: docker-compose up -d

    - name: Set up Database
      run: |
        docker-compose exec -T db mysql -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS app_test;"
        docker-compose exec -T web bin/rails db:schema:load
        docker-compose exec -T web bin/rails db:migrate

    - name: RuboCop
      run: docker-compose exec -T web bundle exec rubocop

    - name: ERBLint
      run: docker-compose exec -T web bundle exec erblint --lint-all

    - name: Precompile assets
      run: docker-compose exec -T web bin/rails assets:precompile

    - name: Rspec
      run: docker-compose exec -T web bundle exec rspec
