name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      run_seed:
        description: "Run seed_fu after db:migrate"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-ecs-deploy.yml
    with:
      environment_name: production
      dockerfile: Dockerfile.prod
      run_seed: ${{ inputs.run_seed || false }}
    secrets: inherit
